global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'ml_serving_api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8000']
        labels:
          service: 'heart-disease-prediction'
          pipeline: 'rizalbasri-pipeline'
